<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;
use Illuminate\Validation\ValidationException;

/**
 * A parent/guardian record.
 *
 * Named ParentGuardian rather than Parent: "parent" is a reserved word in
 * PHP, so `class Parent` is a fatal parse error. The table, routes, views
 * and UI all stay "parents", which keeps the domain language intact.
 */
class ParentGuardian extends Model
{
    use HasFactory;

    /**
     * The table associated with the model.
     *
     * Set explicitly: Eloquent would otherwise derive "parent_guardians"
     * from the class name.
     *
     * @var string
     */
    protected $table = 'parents';

    /**
     * The selectable parent statuses.
     *
     * @var array<int, string>
     */
    public const STATUSES = [
        'Active',
        'Inactive',
    ];

    /**
     * The selectable genders.
     *
     * @var array<int, string>
     */
    public const GENDERS = [
        'Male',
        'Female',
    ];

    /**
     * The ways a parent record can relate to a student.
     *
     * The single source of truth: the pivot enum, the validation rules and
     * both link forms all read this list.
     *
     * @var array<int, string>
     */
    public const RELATIONSHIP_TYPES = [
        'Father',
        'Mother',
        'Guardian',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    // Deliberately excludes parent_id: it is generated by
    // createWithParentId() and must never arrive from a form.
    protected $fillable = [
        'photo',
        'full_name',
        'father_name',
        'gender',
        'cnic_number',
        'mobile_number',
        'alternate_mobile',
        'email',
        'address',
        'occupation',
        'parent_status',
        'notes',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'created_at' => 'datetime',
            'updated_at' => 'datetime',
        ];
    }

    /**
     * Create a parent, assigning the next unique parent ID.
     *
     * The ID is allocated inside a transaction that locks the rows it reads,
     * so two concurrent creations cannot derive the same value. The unique
     * index is the final guard: if a collision still slips through, the
     * insert is retried with a freshly allocated ID.
     *
     * Mirrors Teacher::createWithTeacherId().
     *
     * @param  array<string, mixed>  $data
     */
    public static function createWithParentId(array $data): self
    {
        $attempts = 0;

        while (true) {
            try {
                return DB::transaction(function () use ($data) {
                    $parent = new self($data);

                    // Not mass assigned: set on the instance directly.
                    $parent->parent_id = self::nextParentId();
                    $parent->save();

                    return $parent;
                });
            } catch (UniqueConstraintViolationException $e) {
                if (++$attempts >= 3) {
                    throw $e;
                }
            }
        }
    }

    /**
     * Work out the next parent ID for the current year.
     *
     * Only IDs matching PAR-{year}- are considered, so manually entered
     * legacy IDs are ignored rather than renumbered.
     */
    public static function nextParentId(): string
    {
        $year = date('Y');
        $prefix = "PAR-{$year}-";

        $lastNumber = self::where('parent_id', 'like', "{$prefix}%")
            ->lockForUpdate()
            ->orderByDesc('parent_id')
            ->value('parent_id');

        $nextNumber = $lastNumber ? ((int) substr($lastNumber, strlen($prefix))) + 1 : 1;

        return $prefix . str_pad((string) $nextNumber, 4, '0', STR_PAD_LEFT);
    }

    /**
     * Get the students linked to this parent.
     */
    public function students()
    {
        return $this->belongsToMany(Student::class, 'parent_student', 'parent_id', 'student_id')
            ->using(ParentStudent::class)
            ->withPivot(['id', 'relationship_type', 'is_primary'])
            ->withTimestamps();
    }

    /**
     * Create a basic father record for a student and link it to them.
     *
     * A new record every time, deliberately. No existing parent is searched
     * for or reused: one father may give a different mobile number for each
     * child, so a number identifies nobody reliably, and a wrong reuse
     * silently attaches a child to the wrong family. Two records for one man
     * is the safer failure, and the admin resolves it from Parent Management
     * by completing the right record (CNIC and the rest) and relinking by
     * hand. Automatic merging and duplicate detection are out of scope.
     *
     * Nothing is invented: only the father's name and mobile as recorded on
     * the student, which is all either flow knows about him. A student
     * missing either one is left without a parent rather than given an
     * incomplete record; the admin links one by hand afterwards.
     *
     * The mother is deliberately not handled: a student carries a
     * mother_mobile but no mother name, and a parent record will not be
     * built from a number alone.
     *
     * Shared by the admission approval and by manual student creation, so
     * both produce the same father record and the same link. Callers run it
     * inside their own transaction, which rolls this back with everything
     * else should the rest of the creation fail.
     */
    public static function createFatherFor(Student $student): ?self
    {
        $name = trim((string) $student->father_name);
        $mobile = trim((string) $student->father_mobile);

        // A parent record needs at least a name and a mobile to satisfy the
        // rules the Parent forms enforce.
        if ($name === '' || $mobile === '') {
            return null;
        }

        $parent = self::createWithParentId([
            'full_name' => $name,
            'mobile_number' => $mobile,
            // The link being created is Father, so the record is a man's.
            'gender' => 'Male',
            'parent_status' => 'Active',
        ]);

        $parent->linkStudent($student->id, 'Father', true);

        return $parent;
    }

    /**
     * Link a student to this parent.
     *
     * The read and the insert share one transaction, and the student's
     * existing links are locked for the duration: two concurrent requests
     * cannot both pass the "only one primary per relationship type" check
     * and then both insert. The duplicate rule has the unique index behind
     * it as well; the primary rule cannot (a partial unique index is not
     * portable to MySQL), so it is re-checked here under the lock.
     *
     * @throws ValidationException
     */
    public function linkStudent(int $studentId, string $relationshipType, bool $isPrimary = false): void
    {
        DB::transaction(function () use ($studentId, $relationshipType, $isPrimary) {
            // One locked read serves both checks below.
            $existing = DB::table('parent_student')
                ->where('student_id', $studentId)
                ->lockForUpdate()
                ->get();

            if ($existing->contains('parent_id', $this->id)) {
                throw ValidationException::withMessages([
                    'student_id' => 'This student is already linked to this parent.',
                ]);
            }

            if ($isPrimary && $existing->contains(fn ($link) => $link->relationship_type === $relationshipType && (bool) $link->is_primary)) {
                throw ValidationException::withMessages([
                    'is_primary' => "This student already has a primary {$relationshipType}. Remove that primary first.",
                ]);
            }

            $this->students()->attach($studentId, [
                'relationship_type' => $relationshipType,
                'is_primary' => $isPrimary,
            ]);
        });
    }

    /**
     * Unlink a student from this parent.
     *
     * Only the pivot row is removed: both the parent and the student record
     * are left untouched.
     */
    public function unlinkStudent(int $studentId): void
    {
        $this->students()->detach($studentId);
    }

    /**
     * Determine whether the parent currently has a stored photo.
     */
    public function hasPhoto(): bool
    {
        return $this->photo !== null
            && Storage::disk('public')->exists($this->photo);
    }

    /**
     * Get the public URL of the parent's photo, if any.
     */
    public function photoUrl(): ?string
    {
        return $this->hasPhoto()
            ? asset('storage/' . $this->photo)
            : null;
    }

    /**
     * Get the first letter of the name, used as a photo placeholder.
     */
    public function initial(): string
    {
        return mb_strtoupper(mb_substr((string) $this->full_name, 0, 1));
    }

    /**
     * Get the Tailwind badge classes for the parent's status.
     */
    public function statusBadgeClasses(): string
    {
        return $this->parent_status === 'Active'
            ? 'bg-green-100 text-green-800'
            : 'bg-gray-100 text-gray-800';
    }
}
