<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class Teacher extends Model
{
    use HasFactory;

    /**
     * The selectable teacher statuses.
     *
     * @var array<int, string>
     */
    public const STATUSES = [
        'Active',
        'Inactive',
    ];

    /**
     * The selectable genders.
     *
     * @var array<int, string>
     */
    public const GENDERS = [
        'Male',
        'Female',
    ];

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    // Deliberately excludes teacher_id: it is generated by
    // createWithTeacherId() and must never arrive from a form.
    protected $fillable = [
        'photo',
        'full_name',
        'father_name',
        'date_of_birth',
        'gender',
        'cnic_number',
        'mobile_number',
        'alternate_mobile',
        'email',
        'address',
        'qualification',
        'specialization',
        'joining_date',
        'teacher_status',
        'notes',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'date_of_birth' => 'date',
            'joining_date' => 'date',
        ];
    }

    /**
     * Create a teacher, assigning the next unique teacher ID.
     *
     * The ID is allocated inside a transaction that locks the rows it reads,
     * so two concurrent creations cannot derive the same value. The unique
     * index is the final guard: if a collision still slips through, the
     * insert is retried with a freshly allocated ID.
     *
     * Mirrors AdmissionApplication::createWithApplicationNumber().
     *
     * @param  array<string, mixed>  $data
     */
    public static function createWithTeacherId(array $data): self
    {
        $attempts = 0;

        while (true) {
            try {
                return DB::transaction(function () use ($data) {
                    $teacher = new self($data);

                    // Not mass assigned: set on the instance directly.
                    $teacher->teacher_id = self::nextTeacherId();
                    $teacher->save();

                    return $teacher;
                });
            } catch (UniqueConstraintViolationException $e) {
                if (++$attempts >= 3) {
                    throw $e;
                }
            }
        }
    }

    /**
     * Work out the next teacher ID for the current year.
     *
     * Only IDs matching TCH-{year}- are considered, so manually entered
     * legacy IDs are ignored rather than renumbered.
     */
    public static function nextTeacherId(): string
    {
        $year = date('Y');
        $prefix = "TCH-{$year}-";

        $lastNumber = self::where('teacher_id', 'like', "{$prefix}%")
            ->lockForUpdate()
            ->orderByDesc('teacher_id')
            ->value('teacher_id');

        $nextNumber = $lastNumber ? ((int) substr($lastNumber, strlen($prefix))) + 1 : 1;

        return $prefix . str_pad((string) $nextNumber, 4, '0', STR_PAD_LEFT);
    }

    /**
     * Get the classes this teacher teaches.
     */
    public function academicClasses()
    {
        return $this->belongsToMany(AcademicClass::class, 'teacher_class')
            ->withTimestamps();
    }

    /**
     * Determine whether the teacher currently has a stored photo.
     */
    public function hasPhoto(): bool
    {
        return $this->photo !== null
            && Storage::disk('public')->exists($this->photo);
    }

    /**
     * Get the public URL of the teacher's photo, if any.
     */
    public function photoUrl(): ?string
    {
        return $this->hasPhoto()
            ? asset('storage/' . $this->photo)
            : null;
    }

    /**
     * Get the first letter of the name, used as a photo placeholder.
     */
    public function initial(): string
    {
        return mb_strtoupper(mb_substr((string) $this->full_name, 0, 1));
    }

    /**
     * Get the Tailwind badge classes for the teacher's status.
     */
    public function statusBadgeClasses(): string
    {
        return $this->teacher_status === 'Active'
            ? 'bg-green-100 text-green-800'
            : 'bg-gray-100 text-gray-800';
    }
}
