<?php

namespace App\Http\Requests\Admin;

use App\Models\ParentGuardian;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreParentRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            // parent_id is generated by the server and is rejected outright
            // if a request tries to supply one. Uniqueness itself is held by
            // the unique index on parents.parent_id.
            'parent_id' => ['nullable', 'prohibited'],
            'photo' => ['nullable', 'image', 'mimes:jpeg,jpg,png', 'max:2048'],
            'full_name' => ['required', 'string', 'max:255'],
            'father_name' => ['nullable', 'string', 'max:255'],
            'gender' => ['required', Rule::in(ParentGuardian::GENDERS)],
            'cnic_number' => ['nullable', 'string', 'max:255'],
            'mobile_number' => ['required', 'string', 'max:255'],
            'alternate_mobile' => ['nullable', 'string', 'max:255'],
            'email' => ['nullable', 'email', 'max:255'],
            'address' => ['nullable', 'string'],
            'occupation' => ['nullable', 'string', 'max:255'],
            'parent_status' => ['required', Rule::in(ParentGuardian::STATUSES)],
            'notes' => ['nullable', 'string'],
        ];
    }

    /**
     * Get the custom validation messages.
     *
     * @return array<string, string>
     */
    public function messages(): array
    {
        return [
            'parent_id.prohibited' => 'The parent ID is generated automatically and cannot be set.',
            'photo.image' => 'The photo must be an image file.',
            'photo.mimes' => 'The photo must be a JPG, JPEG or PNG file.',
            'photo.max' => 'The photo may not be larger than 2MB.',
        ];
    }
}
